site_name: UnitySVC Provider SDK
site_description: Local-first service data management for UnitySVC platform
site_author: UnitySVC Team
site_url: https://unitysvc-services.readthedocs.io

repo_name: unitysvc/unitysvc-services
repo_url: https://github.com/unitysvc/unitysvc-services
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - autorefs

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
      - Installation & Quick Start: getting-started.md
      - Data Structure: data-structure.md
      - Workflows: workflows.md
  - Reference:
      - CLI Commands: cli-reference.md
      - File Schemas: file-schemas.md
      - Python API: api-reference.md
  - Development:
      - Development Guide: development.md
      - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/unitysvc/unitysvc-services
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/unitysvc-services/

copyright: Copyright &copy; 2024 UnitySVC
